import { FileText, Loader2, Search } from "lucide-react";
import { useMemo, useState } from "react";
import { useLocation } from "wouter";
import { trpc } from "@/lib/trpc";
import { Input } from "@/components/ui/input";

export default function Library() {
  const [query, setQuery] = useState("");
  const [, setLocation] = useLocation();
  const tasks = trpc.tasks.list.useQuery();
  const filtered = useMemo(() => (tasks.data ?? []).filter(task => `${task.title} ${task.goal}`.toLowerCase().includes(query.toLowerCase())), [query, tasks.data]);
  return <main className="min-h-screen px-5 py-7 sm:px-8 lg:px-10"><header className="border-b border-white/8 pb-5"><p className="text-xs font-semibold uppercase tracking-[.18em] text-orange-300">Library</p><h1 className="mt-1 text-2xl font-semibold text-[#fff7eb]">Task deliverables and history</h1><p className="mt-2 text-sm text-[#a9998a]">Browse only artifacts and event histories generated by your tasks.</p></header><div className="relative mt-7 max-w-xl"><Search className="absolute left-3 top-3 text-[#857567]" size={16} /><Input value={query} onChange={event => setQuery(event.target.value)} placeholder="Search your tasks" className="border-white/10 bg-[#1d1611] pl-10 text-[#f3e6d7] placeholder:text-[#77695c]" /></div>{tasks.isLoading ? <div className="mt-10 flex items-center gap-2 text-sm text-[#a69788]"><Loader2 className="animate-spin" size={16} />Loading library…</div> : null}{tasks.isError ? <p role="alert" className="mt-10 text-sm text-rose-300">{tasks.error.message}</p> : null}<div className="mt-7 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{filtered.map(task => <button key={task.id} onClick={() => setLocation(`/tasks/${task.id}`)} className="rounded-2xl border border-white/8 bg-[#1e1712] p-5 text-left hover:border-orange-300/25"><FileText className="text-orange-300" size={18} /><h2 className="mt-5 truncate text-sm font-semibold text-[#f4e8d9]">{task.title}</h2><p className="mt-2 line-clamp-2 text-xs leading-5 text-[#9e8f80]">{task.goal}</p><span className="mt-5 block text-xs text-orange-200">Open task record →</span></button>)}</div>{!tasks.isLoading && !tasks.isError && filtered.length === 0 ? <div className="mt-10 rounded-2xl border border-dashed border-white/12 p-8 text-center text-sm text-[#9e8e7f]">No task records match this search.</div> : null}</main>;
}
