import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";
import { trpc } from "@/lib/trpc";
import { CheckCircle2, CircleAlert, CreditCard, Database, KeyRound, Loader2, PlugZap, ShieldCheck, UserRound } from "lucide-react";
import { useLocation } from "wouter";

const sections = [{ id: "profile", label: "Profile", icon: UserRound }, { id: "integrations", label: "Integrations", icon: PlugZap }, { id: "model-keys", label: "Model keys", icon: KeyRound }, { id: "memory", label: "Memory", icon: Database }, { id: "security", label: "Security", icon: ShieldCheck }, { id: "billing", label: "Billing", icon: CreditCard }];

export default function Settings() {
  const [location, setLocation] = useLocation();
  const section = location.split("/")[2] ?? "profile";
  const settings = trpc.settings.get.useQuery();
  const readiness = trpc.workspace.serviceReadiness.useQuery();
  const integrations = trpc.workspace.integrations.useQuery();
  const memory = trpc.workspace.memory.useQuery();
  const usage = trpc.workspace.usage.useQuery();
  const removeIntegration = trpc.integrations.remove.useMutation({ onSuccess: () => void integrations.refetch() });
  return <main className="min-h-screen px-5 py-7 sm:px-8 lg:px-10"><header className="border-b border-white/8 pb-5"><p className="text-xs font-semibold uppercase tracking-[.18em] text-orange-300">Settings</p><h1 className="mt-1 text-2xl font-semibold text-[#fff7eb]">Workspace controls</h1></header><div className="mt-7 grid gap-7 lg:grid-cols-[200px_minmax(0,1fr)]"><nav className="space-y-1">{sections.map(item => { const Icon = item.icon; return <button key={item.id} onClick={() => setLocation(`/settings/${item.id}`)} className={cn("flex w-full items-center gap-2 rounded-lg px-3 py-2 text-sm", section === item.id ? "bg-orange-400/10 text-orange-200" : "text-[#a79687] hover:bg-white/5 hover:text-[#ece0d1]")}><Icon size={16} />{item.label}</button>; })}</nav><section className="min-w-0 rounded-2xl border border-white/8 bg-[#1d1611] p-5 sm:p-7">{settings.isLoading && readiness.isLoading ? <div className="flex items-center gap-2 text-sm text-[#a9998a]"><Loader2 className="animate-spin" size={16} />Loading settings…</div> : null}{section === "profile" ? <SettingsProfile settings={settings.data} /> : null}{section === "integrations" ? <SettingsIntegrations readiness={readiness.data ?? []} integrations={integrations.data ?? []} removeIntegration={removeIntegration} /> : null}{section === "model-keys" ? <SettingsModels readiness={readiness.data ?? []} /> : null}{section === "memory" ? <SettingsMemory memory={memory.data ?? []} /> : null}{section === "security" ? <SettingsSecurity /> : null}{section === "billing" ? <SettingsBilling usage={usage.data} /> : null}</section></div></main>;
}

function SettingsProfile({ settings }: { settings: any }) { return <div><h2 className="text-lg font-semibold text-[#f6ebdc]">Profile and preferences</h2><p className="mt-2 text-sm leading-6 text-[#a99a8a]">Preferences are stored on your authenticated account. The current workspace has {settings?.onboardingCompletedAt ? "completed" : "not yet completed"} onboarding.</p></div>; }
function SettingsIntegrations({ readiness, integrations, removeIntegration }: { readiness: Array<any>; integrations: Array<any>; removeIntegration: any }) { const connections = readiness.filter(item => item.category === "integration"); return <div><h2 className="text-lg font-semibold text-[#f6ebdc]">Connected services</h2><p className="mt-2 text-sm text-[#a99a8a]">OAuth connection setup is enabled only after the corresponding server credentials are configured. No credential values are exposed here.</p><div className="mt-6 space-y-2">{connections.map(item => <div key={item.id} className="flex items-center justify-between rounded-xl border border-white/8 bg-white/[.025] p-3"><span className="text-sm text-[#eee2d3]">{item.label}</span><span className={cn("text-xs", item.configured ? "text-emerald-300" : "text-[#938375]")}>{item.configured ? "Configuration ready" : "Not configured"}</span></div>)}</div>{integrations.map(item => <div key={item.id} className="mt-2 flex items-center justify-between rounded-xl border border-white/8 p-3"><span className="text-sm text-[#eee2d3]">{item.provider}</span><Button variant="ghost" size="sm" onClick={() => removeIntegration.mutate({ integrationId: item.id })} disabled={removeIntegration.isPending} className="text-rose-300">Disconnect</Button></div>)}</div>; }
function SettingsModels({ readiness }: { readiness: Array<any> }) { const models = readiness.filter(item => item.category === "model"); return <div><h2 className="text-lg font-semibold text-[#f6ebdc]">Model providers</h2><p className="mt-2 text-sm text-[#a99a8a]">Provider keys are read server-side from the environment. Add or change them through the secure configuration flow.</p><div className="mt-6 grid gap-2 sm:grid-cols-2">{models.map(item => <div key={item.id} className="rounded-xl border border-white/8 bg-white/[.025] p-4"><p className="font-medium text-[#f1e6d8]">{item.label}</p><p className={cn("mt-2 text-xs", item.configured ? "text-emerald-300" : "text-[#958576]")}><span className="mr-1">{item.configured ? "●" : "○"}</span>{item.configured ? item.active ? "Configured and active" : "Configured" : "Not configured"}</p></div>)}</div></div>; }
function SettingsMemory({ memory }: { memory: Array<any> }) { return <div><h2 className="text-lg font-semibold text-[#f6ebdc]">Durable memory</h2><p className="mt-2 text-sm text-[#a99a8a]">Only approved, task-relevant facts are listed here. There are {memory.length} active memory records.</p><div className="mt-6 space-y-2">{memory.map(item => <div key={item.id} className="rounded-xl border border-white/8 bg-white/[.025] p-3"><p className="text-sm text-[#eee2d3]">{item.fact}</p><p className="mt-1 text-xs text-[#8d7d6e]">{item.scope}</p></div>)}</div>{memory.length === 0 ? <div className="mt-6 rounded-xl border border-dashed border-white/12 p-5 text-sm text-[#968677]">No durable facts have been created.</div> : null}</div>; }
function SettingsSecurity() { return <div><h2 className="text-lg font-semibold text-[#f6ebdc]">Security controls</h2><div className="mt-5 space-y-3 text-sm leading-6 text-[#b2a293]"><p className="flex gap-2"><CheckCircle2 size={17} className="mt-0.5 text-emerald-300" />Task ownership is enforced on every task, event, approval, and artifact request.</p><p className="flex gap-2"><CheckCircle2 size={17} className="mt-0.5 text-emerald-300" />High-risk external actions require a server-side approval record before execution.</p><p className="flex gap-2"><CheckCircle2 size={17} className="mt-0.5 text-emerald-300" />Connected-service tokens use envelope encryption when saved through an enabled connection flow.</p></div></div>; }
function SettingsBilling({ usage }: { usage: any }) { return <div><h2 className="text-lg font-semibold text-[#f6ebdc]">Usage and credits</h2><p className="mt-2 text-sm text-[#a99a8a]">Balances and execution usage are derived from the durable ledger.</p><div className="mt-6 grid gap-3 sm:grid-cols-3"><Metric label="Available credits" value={usage?.creditsBalance ?? "—"} /><Metric label="Consumed" value={usage?.creditsConsumed ?? "—"} /><Metric label="Tasks" value={usage?.taskCount ?? "—"} /></div></div>; }
function Metric({ label, value }: { label: string; value: string | number }) { return <div className="rounded-xl border border-white/8 bg-white/[.025] p-4"><p className="text-xs text-[#918172]">{label}</p><p className="mt-2 text-xl font-semibold text-orange-200">{value}</p></div>; }
