import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { cn } from "@/lib/utils";
import { settingsPath } from "@/lib/workspaceLayout";
import { CheckCircle2, CreditCard, Database, KeyRound, Loader2, PlugZap, ShieldCheck, UserRound } from "lucide-react";
import React from "react";
import { useLocation } from "wouter";

const sectionGroups = [
  { label: "Account", sections: [{ id: "profile", label: "Account & preferences", icon: UserRound }] },
  { label: "Agent workspace", sections: [{ id: "model-keys", label: "Model providers", icon: KeyRound }, { id: "integrations", label: "Integrations", icon: PlugZap }, { id: "memory", label: "Durable memory", icon: Database }] },
  { label: "Controls", sections: [{ id: "security", label: "Security", icon: ShieldCheck }, { id: "billing", label: "Usage & credits", icon: CreditCard }] },
];

export default function Settings() {
  const [location, setLocation] = useLocation();
  const section = location.split("/")[2] ?? "profile";
  const settings = trpc.settings.get.useQuery();
  const readiness = trpc.workspace.serviceReadiness.useQuery();
  const integrations = trpc.workspace.integrations.useQuery();
  const memory = trpc.workspace.memory.useQuery();
  const usage = trpc.workspace.usage.useQuery();
  const removeIntegration = trpc.integrations.remove.useMutation({ onSuccess: () => void integrations.refetch() });
  return <main className="synthia-utility-page"><header className="synthia-utility-header"><p>Settings</p><h1>Workspace controls</h1><span>Manage account preferences, agent capabilities, security boundaries, and durable workspace usage.</span></header><div className="mt-5 grid gap-5 lg:grid-cols-[196px_minmax(0,1fr)]"><SettingsSectionNav section={section} onNavigate={setLocation} /><section className="synthia-settings-panel">{settings.isLoading && readiness.isLoading ? <div className="flex items-center gap-2 text-xs text-[#a9998a]"><Loader2 className="animate-spin" size={14} />Loading settings…</div> : null}{section === "profile" ? <SettingsProfile settings={settings.data} /> : null}{section === "integrations" ? <SettingsIntegrations readiness={readiness.data ?? []} integrations={integrations.data ?? []} removeIntegration={removeIntegration} /> : null}{section === "model-keys" ? <SettingsModels readiness={readiness.data ?? []} /> : null}{section === "memory" ? <SettingsMemory memory={memory.data ?? []} /> : null}{section === "security" ? <SettingsSecurity /> : null}{section === "billing" ? <SettingsBilling usage={usage.data} /> : null}</section></div></main>;
}

export function SettingsSectionNav({ section, onNavigate }: { section: string; onNavigate: (path: string) => void }) {
  return <nav className="synthia-settings-nav" aria-label="Settings sections">{sectionGroups.map(group => <div key={group.label} className="synthia-settings-group"><p>{group.label}</p>{group.sections.map(item => { const Icon = item.icon; return <button key={item.id} onClick={() => onNavigate(settingsPath(item.id))} className={cn(section === item.id && "active")}><Icon size={14} />{item.label}</button>; })}</div>)}</nav>;
}

function SettingsProfile({ settings }: { settings: any }) { return <div><h2 className="text-lg font-semibold text-[#f6ebdc]">Account and preferences</h2><p className="mt-2 text-sm leading-6 text-[#a99a8a]">Profile identity is managed through the secure Synthia sign-in boundary. The current workspace has {settings?.onboardingCompletedAt ? "completed" : "not yet completed"} onboarding.</p><div className="mt-6 grid gap-3 sm:grid-cols-2"><SettingSummary label="Profile" value="Managed through Synthia sign-in" /><SettingSummary label="Workspace preference" value="Compact task workspace" /></div></div>; }
function SettingsIntegrations({ readiness, integrations, removeIntegration }: { readiness: Array<any>; integrations: Array<any>; removeIntegration: any }) { const connections = readiness.filter(item => item.category === "integration"); return <div><h2 className="text-lg font-semibold text-[#f6ebdc]">Connected services</h2><p className="mt-2 text-sm text-[#a99a8a]">OAuth connection setup is enabled only after the corresponding server credentials are configured. No credential values are exposed here.</p><div className="mt-6 space-y-2">{connections.map(item => <div key={item.id} className="flex items-center justify-between rounded-xl border border-white/8 bg-white/[.025] p-3"><span className="text-sm text-[#eee2d3]">{item.label}</span><span className={cn("text-xs", item.configured ? "text-emerald-300" : "text-[#938375]")}>{item.configured ? "Configuration ready" : "Not configured"}</span></div>)}</div>{integrations.map(item => <div key={item.id} className="mt-2 flex items-center justify-between rounded-xl border border-white/8 p-3"><span className="text-sm text-[#eee2d3]">{item.provider}</span><Button variant="ghost" size="sm" onClick={() => removeIntegration.mutate({ integrationId: item.id })} disabled={removeIntegration.isPending} className="text-rose-300">Disconnect</Button></div>)}</div>; }
function SettingsModels({ readiness }: { readiness: Array<any> }) { const models = readiness.filter(item => item.category === "model"); return <div><h2 className="text-lg font-semibold text-[#f6ebdc]">Model providers</h2><p className="mt-2 text-sm text-[#a99a8a]">Provider keys are read server-side from the environment. Add or change them through the secure configuration flow.</p><div className="mt-6 grid gap-2 sm:grid-cols-2">{models.map(item => <div key={item.id} className="rounded-xl border border-white/8 bg-white/[.025] p-4"><p className="font-medium text-[#f1e6d8]">{item.label}</p><p className={cn("mt-2 text-xs", item.configured ? "text-emerald-300" : "text-[#958576]")}><span className="mr-1">{item.configured ? "●" : "○"}</span>{item.configured ? item.active ? "Configured and active" : "Configured" : "Not configured"}</p></div>)}</div></div>; }
function SettingsMemory({ memory }: { memory: Array<any> }) { return <div><h2 className="text-lg font-semibold text-[#f6ebdc]">Durable memory</h2><p className="mt-2 text-sm text-[#a99a8a]">Only approved, task-relevant facts are listed here. There are {memory.length} active memory records.</p><div className="mt-6 space-y-2">{memory.map(item => <div key={item.id} className="rounded-xl border border-white/8 bg-white/[.025] p-3"><p className="text-sm text-[#eee2d3]">{item.fact}</p><p className="mt-1 text-xs text-[#8d7d6e]">{item.scope}</p></div>)}</div>{memory.length === 0 ? <div className="mt-6 rounded-xl border border-dashed border-white/12 p-5 text-sm text-[#968677]">No durable facts have been created.</div> : null}</div>; }
function SettingsSecurity() { return <div><h2 className="text-lg font-semibold text-[#f6ebdc]">Security controls</h2><div className="mt-5 space-y-3 text-sm leading-6 text-[#b2a293]"><p className="flex gap-2"><CheckCircle2 size={17} className="mt-0.5 text-emerald-300" />Task ownership is enforced on every task, event, approval, and artifact request.</p><p className="flex gap-2"><CheckCircle2 size={17} className="mt-0.5 text-emerald-300" />High-risk external actions require a server-side approval record before execution.</p><p className="flex gap-2"><CheckCircle2 size={17} className="mt-0.5 text-emerald-300" />Connected-service tokens use envelope encryption when saved through an enabled connection flow.</p></div></div>; }
function SettingsBilling({ usage }: { usage: any }) { return <div><h2 className="text-lg font-semibold text-[#f6ebdc]">Usage and credits</h2><p className="mt-2 text-sm text-[#a99a8a]">Balances and execution usage are derived from the durable ledger.</p><div className="mt-6 grid gap-3 sm:grid-cols-3"><Metric label="Available credits" value={usage?.creditsBalance ?? "—"} /><Metric label="Consumed" value={usage?.creditsConsumed ?? "—"} /><Metric label="Tasks" value={usage?.taskCount ?? "—"} /></div></div>; }
function Metric({ label, value }: { label: string; value: string | number }) { return <div className="rounded-xl border border-white/8 bg-white/[.025] p-4"><p className="text-xs text-[#918172]">{label}</p><p className="mt-2 text-xl font-semibold text-orange-200">{value}</p></div>; }
function SettingSummary({ label, value }: { label: string; value: string }) { return <div className="rounded-xl border border-white/8 bg-white/[.025] p-4"><p className="text-xs text-[#918172]">{label}</p><p className="mt-2 text-sm font-medium text-[#eee2d3]">{value}</p></div>; }
