import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { cn } from "@/lib/utils";
import { trpc } from "@/lib/trpc";
import { useTaskEventStream } from "@/hooks/useTaskEventStream";
import { AlertTriangle, Bot, Check, ChevronLeft, CirclePause, Code2, FileCode2, FileText, FolderTree, ListTree, Loader2, MonitorDot, Play, Send, Square, TerminalSquare, X } from "lucide-react";
import { FormEvent, useMemo, useState } from "react";
import { Link, useLocation, useRoute } from "wouter";

type WorkspaceTab = "screen" | "code" | "terminal" | "files" | "timeline" | "plan";

const statusColor: Record<string, string> = { queued: "text-amber-300", booting: "text-amber-300", planning: "text-orange-300", running: "text-orange-300", needs_input: "text-rose-300", paused: "text-[#b6a99b]", completed: "text-emerald-300", failed: "text-rose-300", cancelled: "text-[#b6a99b]" };

function localTime(value: Date | string | number | null | undefined) { return value ? new Date(value).toLocaleString() : "—"; }
function asRecord(value: unknown) { return value && typeof value === "object" ? value as Record<string, unknown> : {}; }

export default function TaskWorkspace({ replayMode = false }: { replayMode?: boolean }) {
  const route = replayMode ? useRoute("/tasks/:taskId/replay") : useRoute("/tasks/:taskId");
  const taskId = route[1]?.taskId;
  const [, setLocation] = useLocation();
  const [tab, setTab] = useState<WorkspaceTab>("code");
  const [message, setMessage] = useState("");
  const [replayCursor, setReplayCursor] = useState<number | undefined>();
  const snapshot = trpc.tasks.get.useQuery({ taskId: taskId ?? "00000000-0000-4000-8000-000000000000" }, { enabled: Boolean(taskId), refetchInterval: 10_000 });
  const { connected } = useTaskEventStream(taskId);
  const utils = trpc.useUtils();
  const addMessage = trpc.tasks.addMessage.useMutation({ onSuccess: () => { setMessage(""); void utils.tasks.get.invalidate({ taskId }); } });
  const pause = trpc.tasks.pause.useMutation({ onSuccess: () => void utils.tasks.get.invalidate({ taskId }) });
  const resume = trpc.tasks.resume.useMutation({ onSuccess: () => void utils.tasks.get.invalidate({ taskId }) });
  const cancel = trpc.tasks.cancel.useMutation({ onSuccess: () => void utils.tasks.get.invalidate({ taskId }) });
  const resolveApproval = trpc.approvals.resolve.useMutation({ onSuccess: () => void utils.tasks.get.invalidate({ taskId }) });
  const data = snapshot.data;
  const task = data?.task;
  const events = useMemo(() => replayCursor === undefined ? data?.events ?? [] : (data?.events ?? []).filter(event => event.sequenceNumber <= replayCursor), [data?.events, replayCursor]);

  function sendMessage(event: FormEvent) { event.preventDefault(); if (taskId && message.trim()) addMessage.mutate({ taskId, content: message.trim() }); }
  if (snapshot.isLoading) return <div className="grid min-h-screen place-items-center text-sm text-[#a89889]"><Loader2 className="mr-2 animate-spin" size={16} />Loading task workspace…</div>;
  if (snapshot.isError || !task || !taskId) return <main className="p-8"><Link href="/" className="text-sm text-orange-300">← Back to tasks</Link><p role="alert" className="mt-5 text-rose-300">{snapshot.error?.message ?? "The requested task is unavailable."}</p></main>;

  const tabs: Array<{ id: WorkspaceTab; label: string; icon: typeof Code2 }> = [{ id: "screen", label: "Screen", icon: MonitorDot }, { id: "code", label: "Code", icon: Code2 }, { id: "terminal", label: "Terminal", icon: TerminalSquare }, { id: "files", label: "Files", icon: FolderTree }, { id: "timeline", label: "Timeline", icon: ListTree }, { id: "plan", label: "Plan", icon: FileText }];
  const activeApprovals = data.approvals.filter(approval => approval.status === "pending");

  return <div className="synthia-workspace">
    <header className="synthia-workspace-header"><div className="min-w-0"><button onClick={() => setLocation("/")} className="flex items-center gap-1 text-[11px] text-[#a69788] hover:text-orange-300"><ChevronLeft size={13} /> Tasks</button><h1 className="mt-0.5 truncate text-sm font-semibold text-[#f9eddf]">{task.title}</h1></div><div className="flex items-center gap-2"><span className={cn("hidden text-[11px] font-medium sm:inline", statusColor[task.status])}>{task.status.replace(/_/g, " ")}</span><span title={connected ? "Live task stream connected" : "Reconnecting task stream"} className={cn("h-1.5 w-1.5 rounded-full", connected ? "bg-emerald-400" : "bg-amber-400 animate-pulse")} />{task.status === "running" || task.status === "planning" || task.status === "booting" ? <Button size="sm" variant="outline" onClick={() => pause.mutate({ taskId })} disabled={pause.isPending} className="h-7 border-white/12 bg-transparent px-2 text-[11px] text-[#dfd1c1] hover:bg-white/5"><CirclePause size={13} />Pause</Button> : null}{task.status === "paused" || task.status === "needs_input" ? <Button size="sm" onClick={() => resume.mutate({ taskId })} disabled={resume.isPending} className="h-7 bg-orange-400 px-2 text-[11px] text-[#2b170c] hover:bg-orange-300"><Play size={13} />Resume</Button> : null}{!["completed", "failed", "cancelled"].includes(task.status) ? <Button size="sm" variant="ghost" onClick={() => cancel.mutate({ taskId })} disabled={cancel.isPending} className="h-7 px-2 text-[11px] text-[#a89889] hover:text-rose-300"><Square size={12} />Stop</Button> : null}</div></header>
    <div className="grid min-h-[calc(100vh-3.5rem)] lg:grid-cols-[minmax(320px,.9fr)_minmax(480px,1.2fr)]">
      <section className="flex min-h-0 flex-col border-r border-white/8">
        <div className="border-b border-white/8 px-4 py-4 sm:px-5"><p className="text-[9px] font-semibold uppercase tracking-[.16em] text-orange-300">Task objective</p><p className="mt-1.5 max-w-3xl text-xs leading-5 text-[#d6c8b8]">{task.goal}</p>{replayMode ? <div className="mt-3 rounded-md border border-orange-300/20 bg-orange-300/5 px-2.5 py-1.5 text-[11px] text-orange-100">Replay mode — move through the durable event record without changing task execution.</div> : null}</div>
        <div className="min-h-0 flex-1 space-y-3 overflow-y-auto px-4 py-4 sm:px-5">
          {data.messages.length === 0 ? <div className="rounded-lg border border-dashed border-white/12 p-4 text-xs text-[#968678]">No narrated messages have been recorded yet. Status and tool events remain visible in the Agent’s Computer.</div> : null}
          {data.messages.map(entry => <article key={entry.id} className={cn("max-w-[92%] rounded-xl px-3 py-2.5", entry.role === "user" ? "ml-auto bg-orange-400/12 text-orange-50" : "border border-white/8 bg-white/[.035] text-[#e6dbce]")}><p className="mb-1 text-[9px] font-semibold uppercase tracking-[.13em] text-[#9d8d7d]">{entry.role === "agent" ? "Synthia" : entry.role}</p><p className="whitespace-pre-wrap text-xs leading-5">{entry.content}</p><time className="mt-1.5 block text-[9px] text-[#7c6e60]">{localTime(entry.createdAt)}</time></article>)}
          {activeApprovals.map(approval => <article key={approval.id} className="rounded-xl border border-amber-300/25 bg-amber-300/[.07] p-3"><div className="flex items-start gap-2.5"><AlertTriangle className="mt-0.5 text-amber-300" size={16} /><div><p className="text-xs font-semibold text-amber-100">Approval required</p><p className="mt-1 text-xs leading-5 text-[#dccdb8]">{approval.description}</p><p className="mt-1.5 text-[11px] text-[#a89983]">Tool: {approval.toolName} · Risk: {approval.riskLevel}</p><div className="mt-3 flex gap-2"><Button size="sm" onClick={() => resolveApproval.mutate({ taskId, approvalId: approval.id, decision: "approved" })} disabled={resolveApproval.isPending} className="h-7 bg-amber-300 px-2 text-[11px] text-[#2c1b0d] hover:bg-amber-200"><Check size={13} />Approve</Button><Button size="sm" variant="outline" onClick={() => resolveApproval.mutate({ taskId, approvalId: approval.id, decision: "rejected" })} disabled={resolveApproval.isPending} className="h-7 border-amber-200/25 bg-transparent px-2 text-[11px] text-amber-100 hover:bg-amber-300/10"><X size={13} />Reject</Button></div></div></div></article>)}
        </div>
        {!replayMode ? <form onSubmit={sendMessage} className="border-t border-white/8 p-3"><label className="sr-only" htmlFor="task-message">Send a message to Synthia</label><div className="flex gap-2"><Input id="task-message" value={message} onChange={event => setMessage(event.target.value)} placeholder="Add a constraint or answer Synthia…" className="h-8 border-white/10 bg-[#1c1510] text-xs text-[#f5e9da] placeholder:text-[#77695c]" /><Button type="submit" size="icon" disabled={!message.trim() || addMessage.isPending} className="h-8 w-8 shrink-0 bg-orange-400 text-[#2a170b] hover:bg-orange-300"><Send size={14} /></Button></div>{addMessage.isError ? <p role="alert" className="mt-2 text-[11px] text-rose-300">{addMessage.error.message}</p> : null}</form> : null}
      </section>
      <aside className="flex min-h-0 flex-col bg-[#19130f]" aria-label="Agent's Computer">
        <div className="flex items-center justify-between border-b border-white/8 px-4 py-3"><div><p className="flex items-center gap-2 text-xs font-semibold text-[#f6eadb]"><Bot size={15} className="text-orange-300" />Agent’s Computer</p><p className="mt-0.5 text-[10px] text-[#887869]">Open workspace · <span className="text-orange-200">Code</span> selected</p></div>{data.sandboxes[0] ? <span className="rounded-full bg-emerald-400/10 px-2 py-1 text-[9px] text-emerald-300">Sandbox {data.sandboxes[0].status}</span> : <span className="rounded-full bg-white/5 px-2 py-1 text-[9px] text-[#9c8c7d]">No sandbox yet</span>}</div>
        <div className="flex overflow-x-auto border-b border-white/8 px-2" role="tablist" aria-label="Agent workspace panels">{tabs.map(item => { const Icon = item.icon; return <button key={item.id} role="tab" aria-selected={tab === item.id} onClick={() => setTab(item.id)} className={cn("flex h-9 shrink-0 items-center gap-1.5 border-b-2 px-2.5 text-[11px]", tab === item.id ? "border-orange-400 text-orange-200" : "border-transparent text-[#887869] hover:text-[#d6c7b5]")}><Icon size={13} />{item.label}</button>; })}</div>
        <div className="min-h-0 flex-1 overflow-y-auto p-3">
          {tab === "code" ? <CodePanel deliverables={data.deliverables} events={events} onOpenTab={setTab} /> : null}
          {tab === "screen" ? <ScreenPanel deliverables={data.deliverables} /> : null}
          {tab === "terminal" ? <TerminalPanel events={events} /> : null}
          {tab === "files" ? <FilesPanel deliverables={data.deliverables} /> : null}
          {tab === "timeline" ? <TimelinePanel events={events} replayMode={replayMode} replayCursor={replayCursor} setReplayCursor={setReplayCursor} allEvents={data.events} /> : null}
          {tab === "plan" ? <PlanPanel plan={task.plan as Array<any>} /> : null}
        </div>
      </aside>
    </div>
  </div>;
}

function CodePanel({ deliverables, events, onOpenTab }: { deliverables: Array<any>; events: Array<any>; onOpenTab: (tab: WorkspaceTab) => void }) {
  const terminalEvents = events.filter(event => ["tool_call", "tool_result", "error"].includes(event.type));
  const latestEvent = events.at(-1);
  return <div className="grid h-full min-h-[440px] grid-rows-[minmax(250px,1fr)_auto] overflow-hidden rounded-lg border border-white/8 bg-[#12100e]"><div className="grid min-h-0 grid-cols-[140px_minmax(0,1fr)]"><div className="border-r border-white/8 p-3"><p className="mb-2 text-[9px] font-semibold uppercase tracking-[.15em] text-[#76675a]">Workspace files</p>{deliverables.length === 0 ? <p className="text-[11px] leading-5 text-[#887869]">No files emitted by this task yet.</p> : deliverables.map(item => <div key={item.id} className="mb-1.5 flex items-center gap-1.5 text-[11px] text-[#d5c5b3]"><FileCode2 size={12} className="text-orange-300" /><span className="truncate">{item.filename}</span></div>)}</div><div className="min-w-0 overflow-y-auto p-3"><p className="font-mono text-[11px] text-[#6f9d6e]">// Editor context · agent tool output</p><pre className="mt-3 whitespace-pre-wrap font-mono text-[11px] leading-5 text-[#c9c0b7]">{events.filter(event => event.type === "tool_result").map(event => JSON.stringify(asRecord(event.payload), null, 2)).join("\n\n") || "Waiting for the agent to emit workspace files or code-tool output."}</pre></div></div><div className="grid grid-cols-3 gap-px border-t border-white/8 bg-white/8"><button onClick={() => onOpenTab("terminal")} className="min-w-0 bg-[#15110d] p-2.5 text-left hover:bg-white/[.035]"><span className="flex items-center gap-1 text-[9px] font-semibold uppercase tracking-[.13em] text-orange-300"><TerminalSquare size={11} />Terminal</span><p className="mt-1.5 truncate font-mono text-[10px] text-[#bdae9e]">{terminalEvents.length ? `${terminalEvents.length} recorded tool event${terminalEvents.length === 1 ? "" : "s"}` : "No terminal output"}</p></button><button onClick={() => onOpenTab("timeline")} className="min-w-0 bg-[#15110d] p-2.5 text-left hover:bg-white/[.035]"><span className="flex items-center gap-1 text-[9px] font-semibold uppercase tracking-[.13em] text-orange-300"><ListTree size={11} />Timeline</span><p className="mt-1.5 truncate text-[10px] text-[#bdae9e]">{latestEvent ? `#${latestEvent.sequenceNumber} · ${latestEvent.type}` : "No events yet"}</p></button><button onClick={() => onOpenTab("files")} className="min-w-0 bg-[#15110d] p-2.5 text-left hover:bg-white/[.035]"><span className="flex items-center gap-1 text-[9px] font-semibold uppercase tracking-[.13em] text-orange-300"><FileText size={11} />Artifacts</span><p className="mt-1.5 truncate text-[10px] text-[#bdae9e]">{deliverables.length ? `${deliverables.length} published` : "No artifacts"}</p></button></div></div>;
}
function ScreenPanel({ deliverables }: { deliverables: Array<any> }) { const frame = deliverables.find(item => String(item.mimeType ?? "").startsWith("image/")); return <div className="grid min-h-[480px] place-items-center rounded-xl border border-white/8 bg-[#11100e] p-6 text-center">{frame?.url ? <img src={frame.url} alt={`Sandbox capture ${frame.filename}`} className="max-h-[520px] rounded-lg" /> : <div><MonitorDot className="mx-auto text-[#736559]" size={32} /><p className="mt-3 text-sm text-[#a59686]">A sandbox screen frame appears here when capture is available.</p><p className="mt-1 max-w-sm text-xs leading-5 text-[#78695d]">Live browser interaction and screen capture require an E2B desktop sandbox. The local Docker fallback is intentionally code-only and does not include a graphical browser.</p></div>}</div>; }
function TerminalPanel({ events }: { events: Array<any> }) { const output = events.filter(event => ["tool_call", "tool_result", "error"].includes(event.type)); return <div className="min-h-[480px] rounded-xl border border-white/8 bg-[#11100e] p-4 font-mono text-xs leading-6">{output.length === 0 ? <span className="text-[#796b5e]">No terminal or tool output has been produced for this task.</span> : output.map(event => <div key={event.id} className="mb-3"><span className="text-orange-300">[{event.type}]</span><pre className="whitespace-pre-wrap text-[#cfc5b9]">{JSON.stringify(asRecord(event.payload), null, 2)}</pre></div>)}</div>; }
function FilesPanel({ deliverables }: { deliverables: Array<any> }) { return <div>{deliverables.length === 0 ? <div className="rounded-xl border border-dashed border-white/12 p-6 text-sm text-[#988879]">No deliverables have been published by this task.</div> : <div className="space-y-2">{deliverables.map(item => <a key={item.id} href={item.url} target="_blank" rel="noreferrer" className="flex items-center gap-3 rounded-xl border border-white/8 bg-white/[.025] p-3 hover:border-orange-300/25"><FileText className="text-orange-300" size={17} /><span className="min-w-0 flex-1"><b className="block truncate text-sm text-[#f0e3d4]">{item.filename}</b><small className="text-xs text-[#8b7c6e]">{item.mimeType}</small></span><span className="text-xs text-orange-300">Open</span></a>)}</div>}</div>; }
function TimelinePanel({ events, allEvents, replayMode, replayCursor, setReplayCursor }: { events: Array<any>; allEvents: Array<any>; replayMode: boolean; replayCursor: number | undefined; setReplayCursor: (value: number | undefined) => void }) { return <div>{replayMode && allEvents.length > 0 ? <div className="mb-5 rounded-xl border border-orange-300/15 bg-orange-300/[.04] p-3"><label className="text-xs text-orange-100">Replay through event {replayCursor ?? allEvents.at(-1)?.sequenceNumber}</label><input className="mt-3 w-full accent-orange-400" type="range" min={allEvents[0]?.sequenceNumber} max={allEvents.at(-1)?.sequenceNumber} value={replayCursor ?? allEvents.at(-1)?.sequenceNumber} onChange={event => setReplayCursor(Number(event.target.value))} /></div> : null}{events.length === 0 ? <div className="rounded-xl border border-dashed border-white/12 p-6 text-sm text-[#988879]">No task events are available yet.</div> : <ol className="relative ml-2 border-l border-white/10 pl-5">{events.map(event => <li key={event.id} className="relative pb-5"><span className="absolute -left-[1.63rem] top-1.5 h-2 w-2 rounded-full bg-orange-400" /><p className="text-xs font-medium text-[#e7d9c8]">#{event.sequenceNumber} · {event.type.replace(/_/g, " ")}</p><p className="mt-1 text-xs leading-5 text-[#978779]">{JSON.stringify(asRecord(event.payload))}</p><time className="mt-1 block text-[10px] text-[#756658]">{localTime(event.createdAt)}</time></li>)}</ol>}</div>; }
function PlanPanel({ plan }: { plan: Array<any> }) { return <ol className="space-y-3">{plan.map((step, index) => <li key={step.id} className="flex gap-3 rounded-xl border border-white/8 bg-white/[.02] p-3"><span className={cn("grid h-6 w-6 shrink-0 place-items-center rounded-full text-xs", step.state === "done" ? "bg-emerald-400/15 text-emerald-300" : step.state === "active" ? "bg-orange-400/15 text-orange-200" : "bg-white/5 text-[#948476]")}>{index + 1}</span><span><b className="block text-sm font-medium text-[#e9ddcf]">{step.title}</b><small className="mt-1 block text-xs text-[#958677]">{step.state}</small></span></li>)}</ol>; }
