const list = (value?: string) =>
  (value ?? "")
    .split(",")
    .map(item => item.trim().toLowerCase())
    .filter(Boolean);

const modelList = (value?: string) =>
  (value ?? "")
    .split(",")
    .map(item => item.trim())
    .filter(Boolean);

export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  postgresUrl: process.env.SYNTHIA_POSTGRES_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  publicAppUrl: process.env.SYNTHIA_PUBLIC_APP_URL ?? "",
  workerMode: process.env.SYNTHIA_WORKER_MODE ?? "embedded",
  logLevel: process.env.SYNTHIA_LOG_LEVEL ?? "info",
  encryptionKey: process.env.SYNTHIA_ENCRYPTION_KEY ?? "",
  eventRetentionDays: Number(process.env.SYNTHIA_EVENT_RETENTION_DAYS ?? 30),
  sandboxRetentionDays: Number(process.env.SYNTHIA_SANDBOX_RETENTION_DAYS ?? 30),
  maxAgentIterations: Number(process.env.SYNTHIA_MAX_AGENT_ITERATIONS ?? 80),
  taskTimeoutSeconds: Number(process.env.SYNTHIA_TASK_TIMEOUT_SECONDS ?? 7200),
  redisUrl: process.env.REDIS_URL ?? "",
  redisTlsEnabled: process.env.REDIS_TLS_ENABLED === "true",
  sandboxProvider: process.env.SYNTHIA_SANDBOX_PROVIDER ?? "auto",
  e2bApiKey: process.env.E2B_API_KEY ?? "",
  e2bTemplateId: process.env.E2B_TEMPLATE_ID ?? "",
  e2bSandboxTimeoutSeconds: Number(process.env.E2B_SANDBOX_TIMEOUT_SECONDS ?? 82800),
  dockerSandboxImage: process.env.SYNTHIA_DOCKER_SANDBOX_IMAGE ?? "synthia-sandbox:latest",
  sandboxAllowedHosts: list(process.env.SYNTHIA_SANDBOX_ALLOWED_HOSTS),
  sandboxRegion: process.env.SYNTHIA_SANDBOX_REGION ?? "us",
  orchestratorProvider: process.env.SYNTHIA_ORCHESTRATOR_PROVIDER ?? "openrouter",
  orchestratorModel: process.env.SYNTHIA_ORCHESTRATOR_MODEL ?? "",
  subtaskProvider: process.env.SYNTHIA_SUBTASK_PROVIDER ?? "",
  subtaskModel: process.env.SYNTHIA_SUBTASK_MODEL ?? "",
  availableModels: modelList(process.env.SYNTHIA_AVAILABLE_MODELS),
  visionModels: modelList(process.env.SYNTHIA_VISION_MODELS),
  imageProvider: process.env.SYNTHIA_IMAGE_PROVIDER ?? "forge",
  imageModels: modelList(process.env.SYNTHIA_IMAGE_MODELS),
  videoProvider: process.env.SYNTHIA_VIDEO_PROVIDER ?? "",
  videoModels: modelList(process.env.SYNTHIA_VIDEO_MODELS),
  videoApiKey: process.env.SYNTHIA_VIDEO_API_KEY ?? "",
  groqApiKey: process.env.GROQ_API_KEY ?? "",
  openRouterApiKey: process.env.OPENROUTER_API_KEY ?? "",
  openRouterHttpReferer: process.env.OPENROUTER_HTTP_REFERER ?? "",
  openRouterAppName: process.env.OPENROUTER_APP_NAME ?? "Synthia AI",
  geminiApiKey: process.env.GEMINI_API_KEY ?? "",
  deepseekApiKey: process.env.DEEPSEEK_API_KEY ?? "",
  searchPrimary: process.env.SYNTHIA_SEARCH_PRIMARY ?? "tavily",
  tavilyApiKey: process.env.TAVILY_API_KEY ?? "",
  serperApiKey: process.env.SERPER_API_KEY ?? "",
  storageProvider: process.env.SYNTHIA_STORAGE_PROVIDER ?? "r2",
  awsRegion: process.env.AWS_REGION ?? "",
  awsAccessKeyId: process.env.AWS_ACCESS_KEY_ID ?? "",
  awsSecretAccessKey: process.env.AWS_SECRET_ACCESS_KEY ?? "",
  awsS3Bucket: process.env.AWS_S3_BUCKET ?? "",
  awsS3Endpoint: process.env.AWS_S3_ENDPOINT ?? "",
  r2AccountId: process.env.R2_ACCOUNT_ID ?? "",
  r2AccessKeyId: process.env.R2_ACCESS_KEY_ID ?? "",
  r2SecretAccessKey: process.env.R2_SECRET_ACCESS_KEY ?? "",
  r2Bucket: process.env.R2_BUCKET ?? "",
  r2PublicBaseUrl: process.env.R2_PUBLIC_BASE_URL ?? "",
  emailPrimary: process.env.SYNTHIA_EMAIL_PRIMARY ?? "resend",
  emailFrom: process.env.SYNTHIA_EMAIL_FROM ?? "",
  resendApiKey: process.env.RESEND_API_KEY ?? "",
  postmarkServerToken: process.env.POSTMARK_SERVER_TOKEN ?? "",
  postmarkMessageStream: process.env.POSTMARK_MESSAGE_STREAM ?? "outbound",
};
